### ISSUE TITLE
Query Orderable Issue

### ISSUE THREAD

**Issue by edwinsyarief** [yohamta/donburi#144]
I have this component:

```
type OrderableData struct {
	Index int
}

func (o OrderableData) Order() int {
	return o.Index
}

var Orderable = donburi.NewComponentType[OrderableData]()
```

and then I called all entries as follows:

```
orderedEntitiesQuery := donburi.NewOrderedQuery[components.OrderableData](
		filter.Contains(
			components.Orderable,
			components.Bounds,
			...)
orderedEntities := orderedEntitiesQuery.IterOrdered(ecs.World, components.Orderable)

println("start ---")
	for entry := range orderedEntities {
		order := components.Orderable.Get(entry)
		println(order.Index)
		DrawAnimationEntry(entry, viewportEntry, gameplayBuffer)
	}
	println("end ---")
```

I got these results:

![image](https://github.com/user-attachments/assets/c0f73984-e7cf-48bb-a30e-67f027b565ef)

You can see that the value is not correctly ordered. Does my implementation is wrong?

**Comment by yohamta** [comment]
Hi @edwinsyarief, thank you very much for reporting the detailed issue. This is really helpful. The issue is fixed in `v1.15.2` now. Could you please check it and let me know if there're still any issues.

**Comment by edwinsyarief** [comment]
Hi @yohamta , thank you very much for the fast response. The result are now better, but some of them still not consistent, I only changed one object's index, some of them in the world is changing when not moving. Here is the showcase:
[https://imgur.com/a/EqhJBpA](url)

But the result is consistent when I am using the manual way like this:
```
        query := donburi.NewQuery(filter.Contains(components.RenderableEntity))
	sorted := []*donburi.Entry{}
	for entry := range query.Iter(ecs.World) {
		sorted = append(sorted, entry)
	}

	slices.SortStableFunc(sorted, func(a, b *donburi.Entry) int {
		orderA := components.Orderable.Get(a)
		orderB := components.Orderable.Get(b)
		return cmp.Compare(orderA.Index, orderB.Index)
	})
```
Here is the showcase when using slices.SortStableFunc:
[https://imgur.com/a/PKm3p9J](url)

**Comment by yohamta** [comment]
Oh thank you very much. Yes, I agree that I should have used the stable sort. Let me update again.

**Comment by yohamta** [comment]
Hi @edwinsyarief, it should be fixed now.

**Comment by edwinsyarief** [comment]
Yes, it is fixed. 

Thank you very much
